// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	context "context"
	postgresDB "urleater/internal/repository/postgresDB"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// ChangePassword provides a mock function with given fields: ctx, email, password
func (_m *Storage) ChangePassword(ctx context.Context, email string, password string) error {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateShortLink provides a mock function with given fields: ctx, shortLink, longLink, userID
func (_m *Storage) CreateShortLink(ctx context.Context, shortLink string, longLink string, userID string) (*postgresDB.Link, error) {
	ret := _m.Called(ctx, shortLink, longLink, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateShortLink")
	}

	var r0 *postgresDB.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*postgresDB.Link, error)); ok {
		return rf(ctx, shortLink, longLink, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *postgresDB.Link); ok {
		r0 = rf(ctx, shortLink, longLink, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*postgresDB.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, shortLink, longLink, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: ctx, email, password
func (_m *Storage) CreateUser(ctx context.Context, email string, password string) error {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteShortLink provides a mock function with given fields: ctx, shortLink, email
func (_m *Storage) DeleteShortLink(ctx context.Context, shortLink string, email string) error {
	ret := _m.Called(ctx, shortLink, email)

	if len(ret) == 0 {
		panic("no return value specified for DeleteShortLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, shortLink, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExtendShortLink provides a mock function with given fields: ctx, shortLink, expiresAt
func (_m *Storage) ExtendShortLink(ctx context.Context, shortLink string, expiresAt time.Time) (*postgresDB.Link, error) {
	ret := _m.Called(ctx, shortLink, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for ExtendShortLink")
	}

	var r0 *postgresDB.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (*postgresDB.Link, error)); ok {
		return rf(ctx, shortLink, expiresAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) *postgresDB.Link); ok {
		r0 = rf(ctx, shortLink, expiresAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*postgresDB.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, shortLink, expiresAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetShortLink provides a mock function with given fields: ctx, shortLink
func (_m *Storage) GetShortLink(ctx context.Context, shortLink string) (*postgresDB.Link, error) {
	ret := _m.Called(ctx, shortLink)

	if len(ret) == 0 {
		panic("no return value specified for GetShortLink")
	}

	var r0 *postgresDB.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*postgresDB.Link, error)); ok {
		return rf(ctx, shortLink)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *postgresDB.Link); ok {
		r0 = rf(ctx, shortLink)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*postgresDB.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortLink)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSubscriptions provides a mock function with given fields: ctx
func (_m *Storage) GetSubscriptions(ctx context.Context) ([]postgresDB.Subscription, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptions")
	}

	var r0 []postgresDB.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]postgresDB.Subscription, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []postgresDB.Subscription); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]postgresDB.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: ctx, email
func (_m *Storage) GetUser(ctx context.Context, email string) (*postgresDB.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *postgresDB.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*postgresDB.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *postgresDB.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*postgresDB.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserShortLinksWithOffsetAndLimit provides a mock function with given fields: ctx, email, offset, limit
func (_m *Storage) GetUserShortLinksWithOffsetAndLimit(ctx context.Context, email string, offset int, limit int) ([]postgresDB.Link, error) {
	ret := _m.Called(ctx, email, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetUserShortLinksWithOffsetAndLimit")
	}

	var r0 []postgresDB.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]postgresDB.Link, error)); ok {
		return rf(ctx, email, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []postgresDB.Link); ok {
		r0 = rf(ctx, email, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]postgresDB.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, email, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserLinks provides a mock function with given fields: ctx, email, urlsDelta
func (_m *Storage) UpdateUserLinks(ctx context.Context, email string, urlsDelta int) (*postgresDB.User, error) {
	ret := _m.Called(ctx, email, urlsDelta)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserLinks")
	}

	var r0 *postgresDB.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (*postgresDB.User, error)); ok {
		return rf(ctx, email, urlsDelta)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *postgresDB.User); ok {
		r0 = rf(ctx, email, urlsDelta)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*postgresDB.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, email, urlsDelta)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
